=== talziv2/Enigma-3.0/xml-files/Enigma-Ex3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Schema for Exercise 3 - adds "name" attribute to BTE-Enigma -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="BTE-Rotors">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="BTE-Rotor"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BTE-Rotor">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="BTE-Positioning"/>
			</xs:sequence>
			<xs:attribute name="notch" type="xs:int" use="required"/>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="BTE-Reflectors">
		<xs:complexType>
			<xs:sequence maxOccurs="5">
				<xs:element ref="BTE-Reflector"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BTE-Reflector">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="BTE-Reflect"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="I"/>
						<xs:enumeration value="II"/>
						<xs:enumeration value="III"/>
						<xs:enumeration value="IV"/>
						<xs:enumeration value="V"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="BTE-Reflect">
		<xs:complexType>
			<xs:attribute name="input" type="xs:int" use="required"/>
			<xs:attribute name="output" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="BTE-Positioning">
		<xs:complexType>
			<xs:attribute name="left" type="xs:string" use="required"/>
			<xs:attribute name="right" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="BTE-Enigma">
		<xs:complexType>
			<xs:all>
				<xs:element name="ABC" type="xs:string"/>
				<xs:element ref="BTE-Rotors"/>
				<xs:element ref="BTE-Reflectors"/>
			</xs:all>
			<!-- NEW in Exercise 3: name attribute for machine name -->
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="rotors-count" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== talziv2/Enigma-3.0/xml-files/ex3-sanity-small.xml
<?xml version="1.0" encoding="UTF-8"?>
<BTE-Enigma name="sanity" rotors-count="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Enigma-Ex3.xsd">
		<ABC>
			ABCDEF
		</ABC>
		<BTE-Rotors>
			<BTE-Rotor id="1" notch="4">
				<BTE-Positioning right="A" left="F"/>
				<BTE-Positioning right="B" left="E"/>
				<BTE-Positioning right="C" left="D"/>
				<BTE-Positioning right="D" left="C"/>
				<BTE-Positioning right="E" left="B"/>				
				<BTE-Positioning right="F" left="A"/>				
			</BTE-Rotor>
			<BTE-Rotor id="3" notch="2">
				<BTE-Positioning right="A" left="A"/>
				<BTE-Positioning right="B" left="F"/>
				<BTE-Positioning right="C" left="B"/>
				<BTE-Positioning right="D" left="E"/>
				<BTE-Positioning right="E" left="C"/>				
				<BTE-Positioning right="F" left="D"/>				
			</BTE-Rotor>						
			<BTE-Rotor id="2" notch="1">
				<BTE-Positioning right="A" left="E"/>
				<BTE-Positioning right="B" left="B"/>
				<BTE-Positioning right="C" left="D"/>
				<BTE-Positioning right="D" left="F"/>
				<BTE-Positioning right="E" left="C"/>				
				<BTE-Positioning right="F" left="A"/>				
			</BTE-Rotor>						
		</BTE-Rotors>
		<BTE-Reflectors>
			<BTE-Reflector id="I">
				<BTE-Reflect input="1" output="4"/>
				<BTE-Reflect input="2" output="5"/>
				<BTE-Reflect input="3" output="6"/>								
			</BTE-Reflector>
			<BTE-Reflector id="II">
				<BTE-Reflect input="1" output="6"/>
				<BTE-Reflect input="3" output="4"/>
				<BTE-Reflect input="5" output="2"/>
			</BTE-Reflector>			
		</BTE-Reflectors>
</BTE-Enigma>
